### PR TITLE
Reauthenticate update

### PR DESCRIPTION
**Pull request by andrija-olmero**
- On API call error 403, initiate reauthentication flow. 
- Example updated to reflect Java project

### CODE REVIEW

**Comment by andrija-olmero** [comment]
@milos85vasic FYI. 
There will be one additional commit to this PR.

**Comment by milos85vasic** [comment]
@andrija-olmero Understood. Waiting for your commits.

**Comment by andrija-olmero** [comment]
@milos85vasic PR ready.
Successfully tested local connector and local file storage. After updating flags and segments in a local connector, changes are properly propagated to local file storage.

**Comment by milos85vasic** [comment]
@andrija-olmero That is great news!

**Pull request merged**
